/* Number of total columns/semesters: */
window.semesters = 10;

/* List of available colors to toggle a course as completed */
/* The first color is default for selecting options as well, so make sure to choose that one wisely */
window.colors = ["#b1fca4", "#fac6ff", "#a8c9ff"];

// Order of courses matters: do not swap positions. Append at the end.
window.courses = [
    { name: "Biologia Molecular", credits: 5, code: "BMH126", semester: 1},
    { name: "Embriologia", credits: 0, code: "BMH127", semester: 1},
    { name: "Bioquímica I", credits: 0, code: "BQM101", semester: 1},
    { name: "ICF", credits: 0, code: "FFC111", semester: 1},
    { name: "Metodologia Científica", credits: 0, code: "FFP111", semester: 1},
    { name: "Biofísica", credits: 0, code: "FFW112", semester: 1, corequirements: [1]},
    { name: "Química Geral I", credits: 0, code: "IQG114", semester: 1},
    { name: "Cálculo p/ Farmácia", credits: 0, code: "MAC108", semester: 1},
    { name: "PCI I ", credits: 0, code: "BMW203", semester: 2, requirements: [0, 2]},
    { name: "Bioquímica II", credits: 0, code: "BQM103", semester: 2, requirements: [2]},
    { name: "Química Geral II", credits: 0, code: "IQG127", semester: 2, requirements: [6]},
    { name: "Química Orgânica I", credits: 0, code: "IQO120", semester: 2, requirements: [6]},
    { name: "Bioestatística", credits: 0, code: "MAD237", semester: 2},
    { name: "PCI II", credits: 0, code: "BMW204", semester: 3, requirements: [8]},
    { name: "Química Analítica I", credits: 0, code: "IQA123", semester: 3, requirements: [6], corequirements: [15]},
    { name: "Química Analítica Exp. I", credits: 0, code: "IQA124", semester: 3, requirements: [6], corequirements: [14]},
    { name: "Físico-Química ", credits: 0, code: "IQF235", semester: 3, requirements:[7]},
    { name: "Química Orgânica II", credits: 0, code: "IQO230", semester: 3, requirements:[11]},
    { name: "Química Orgânica Exp. I", credits: 0, code: "IQO242", semester: 3, requirements: [10, 11]},
    { name: "Farmacobotânica", credits: 0, code: "FFP600", semester: 4},
    { name: "Iniciação Científica", credits: 0, code: "FFP111", semester: 4, requirements: [4]},
    { name: "Química Analítica II", credits: 0,code: "IQA233", semester: 4, requirements: [14, 15], corequirements: [22]},
    { name: "Química Analítica Exp. II", credits: 0, code: "IQA234", semester: 4, requirements: [14, 15], corequirements: [21]},
    { name: "Bioinorgânica", credits: 0, code: "IQG234", semester: 4, requirements: [10]},
    { name: "Métodos Espectrométricos", credits: 0, code: "IQO220", semester: 4, requirements: [17, 18]},
    { name: "Química Orgânica III", credits: 0, code: "IQO240", semester: 4, requirements: [17]},
    { name: "Farmacocinética e Farmacodinâmica", credits: 4, code: "BMF310", semester: 5, requirements: [9, 13]},
    { name: "Saúde Coletiva", credits: 1, code: "FFC303", semester: 5},
    { name: "Análises Farmacêuticas", credits: 4, code: "FFM302", semester: 5, requirements: [16, 21, 22]},
    { name: "Política de Saúde", credits: 4, code: "FFM311", semester: 5},
    { name: "Microbiologia e Imunologia", credits: 4, code: "IMW360", semester: 5, requirements: [2]},
    { name: "Química Orgânica Exp. II", credits: 4, code: "IQO251", semester: 5, requirements: [18, 24, 25]},
    { name: "Farmacologia Neuroendócrina", credits: 5, code: "BFM320", semester:6, requirements: [13, 26]},
    { name: "Parasitologia", credits: 2, code: "CFP215", semester: 6, requirements: [13, 30]},
    { name: "Micro Imuno Clínica", credits: 4, code: "FFC480", semester: 6, requirements: [30]},
    { name: "Metabolismo Integrado", credits: 4, code: "FFI311", semester: 6, requirements: [9]},
    { name: "Farmacotécnica I", credits: 4, code: "FFM313", semester: 6, requirements: [26]},
    { name: "Farmacognosia I", credits: 4, code: "FFP313", semester: 6, requirements: [19, 25]},
    { name: "Química de Alimentos", credits: 4, code: "FFP324", semester: 6, requirements: [9, 21]},
    { name: "Farmacologia Cardio/Quimio", credits: 5, code: "BMF410", semester: 7, requirements: [13, 32]},
    { name: "Bioquímica Clínica", credits: 2, code: "FFC304", semester: 7, requirements: [9, 13]},
    { name: "Diagnóstico Clínico Laboratorial", credits: 4, code: "FFC321", semester: 7, requirements: [30, 33]},
    { name: "Hematologia", credits: 4, code: "FFC322", semester:7, requirements: [13]},
    { name: "Farmacotécnica II", credits: 4, code: "FFM323", semester: 7, requirements: [36]},
    { name: "Assistência e Atenção Farmacêutica", credits: 4, code: "FFM481", semester: 7, requirements: [32, 36]},
    { name: "Estágio Sup. Farmácia Comunitária", credits: 4, code: "FFM481", semester: 7, requirements: [26, 36]},
    { name: "Farmacognosia II", credits: 4, code: "FFP323", semester: 7, requirements: [37]},
    { name: "Análises de Alimentos", credits: 4, code: "FFP403", semester: 7, requirements: [38]},
    { name: "Parasitologia e Micologia Clínica", credits: 3, code: "FFC406", semester: 8, requirements: [33]},
    { name: "Química Farmacêutica Medicinal", credits: 4, code: "FFI401", semester: 8, requirements: [25, 39]},
    { name: "Farmácia Hospitalar", credits: 4, code: "FFM300", semester: 8, corequirements: [39, 43]},
    { name: "Deonto. e Legisl. Farmacêutica", credits: 3, code: "FFM301", semester: 8},
    { name: "Farmaco-epidemiologia", credits: 4, code: "FFM402", semester: 8, requirements: [12, 27]},
    { name: "Farmacotécnica Hospitalar", credits: 4, code: "FFM403", semester: 8, requirements: [39, 43]},
    { name: "Tecnologia Industria Farmacêutica", credits: 3, code: "FFM408", semester: 8, requirements: [10, 36]},
    { name: "Estág. Sup. Farm. Manip. Alopática", credits: 4, code: "FFMU07", semester: 8, requirements: [43], corequirements: [50]},
    { name: "Bromatologia em Saúde", credits: 4, code: "FFP402", semester: 8, requirements: [38]},
    { name: "Toxicologia Geral", credits: 3, code: "FFC314", semester: 9, requirements:[25, 26]},
    { name: "Controle Bio. Micro. Quali. Pro. Farma.", credits: 4, code: "FFI402", semester: 9, requirements:[26, 30]},
    { name: "Biofarmácia", credits: 4, code: "FFM405", semester: 9, requirements: [43]},
    { name: "Dermocosméticos", credits: 3, code: "FFM406", semester: 9, requirements: [36]},
    { name: "Biotecnologia Farmacêutica", credits: 4, code: "FFM426", semester: 9, requirements: [30]},
    { name: "Estágio Sup. Farmácia Hosp.", credits: 4, code: "FFMU08", semester: 9, requirements: [39, 43, 50]},
    { name: "TCC", credits: 3, code: "FFWK02", semester: 9, requirements: [20]},
    { name: "Economia e Adm, Empr. Farm.", credits: 4, code: "IEEE326", semester: 9},
    { name: "Estágio Sup Especialidades", credits:04, code: "FFWU06", semester: 10},
    { name: "Atividade Comp. (Eletiva Farmácia)", credits: 15, semester: 10, step: 1},
    { name: "Atividade Comp.", credits: 4, semester: 10, step: 1},
    { name: "Atividades Acad. Livre Escolha", credits: 5, semester: 10, step: 1},

]
